### ISSUE TITLE
Unable to re-create environment

### ISSUE THREAD

**Issue by tirohia** [stjudecloud/expression-classification#22]
Mōrena. 

I am unable to recreate a conda environment from the provided yml file. 

Conda initially fails to find three packages:
```
  - gfortran_impl_linux-64==7.5.0=hdf63c60_6
  - gxx_impl_linux-62==7.5.0=hdf63c60_6
  - gcc_impl_linux-64==7.5.0=hd420e75_6

```
removing the =hdf63c60_6 suffix lets conda identify gfortran_impl_linux-64 and gcc_impl_linux-64, but there remains no candidate for gxx_impl_linux-62. There is a gxx_impl_linux-64 though. 
Changing the packages in the environment.yml file to:
```
  - gfortran_impl_linux-64==7.5.0
  - gxx_impl_linux-64==7.5.0
  - gcc_impl_linux-64==7.5.0

```
lets Conda solve the environment, but results in it finding conflicts. It then searches for incompatible package and finds a whole bunch of conflicts (in the attached txt file). Mostly in R packages, so I have no idea if the conflicts are a result of changing the names of the three packages above, or if they're there anyway. 

Thanks
Ben. 
[conflicts.txt](https://github.com/stjudecloud/expression-classification/files/9502736/conflicts.txt)

**Comment by tirohia** [comment]
It's not super important - the more basic environment creation process does work.

**Comment by adthrasher** [comment]
I trimmed down the environment file to match what we are creating in the Docker container. Please try the attached environment file and let me know if it works for you. 

[environment.yml.zip](https://github.com/stjudecloud/expression-classification/files/9527022/environment.yml.zip)

**Comment by tirohia** [comment]
All good. Thanks.
